### ISSUE TITLE
train and test inter dataset

### ISSUE THREAD

**Issue by KimHanBeul** [yuh-yang/MBHT-KDD22#13]
Hello, i was able to check and understand well the dataset preprocessing code you provided at closed issue(Preprocessed dataset...). However, i wonder how to create the train.inter and test.inter dataset you provided in README.md (https://drive.google.com/file/d/1OFT_5Xp_az-GSHIl7QEPB9zhulbooLzE/view?usp=sharing) by the trn_buy, trn_cart, trn_fav, trn_pv and tst_int file made from the preprocessing code you provided. Could you share the code about how to make the train and test .inter file?

**Comment by yuh-yang** [comment]
Hi,

You can refer to this issue (https://github.com/yuh-yang/MBHT-KDD22/issues/6) for the details of preprocessing.
