### ISSUE TITLE
A problem about the negative sampling

### ISSUE THREAD

**Issue by KNwbq** [yuh-yang/MBHT-KDD22#5]
Well, I think there is a problem about the negative sampling in the MBHT-KDD2022 code. Specifically, RecBole will get the used ids before negative sampling, and the relevant code is shown below. When returning iid_field, I found that there is something wrong logically because the iid_field of your datasets' inter_feat is actually the target item but not the clicked item. Or maybe I was wrong.  I would appreciate your reply.

```
for phase, dataset in zip(self.phases, self.datasets):
   cur = np.array([set(s) for s in last])
   for uid, iid in zip(dataset.inter_feat[self.uid_field].numpy(), dataset.inter_feat[self.iid_field].numpy()):
      cur[uid].add(iid)
   last = used_item_id[phase] = cur
```

**Comment by yuh-yang** [comment]
@KNwbq Hi! Thanks for your report. I guess it is really an inherent problem of RecBole if we expect that none of the interacted items should be included in the evaluation negative samples. Actually this setting is consistent with what we do in a full-sort evaluation: we exclude those items that the user treated positive.

I also notice that in the [latest version of RecBole](https://github.com/RUCAIBox/RecBole/blob/master/recbole/sampler/sampler.py), the bug remains still. Maybe you should open an issue in the official repository and get me involved in the discussion if necessary.

**Comment by KNwbq** [comment]
Thank you for your reply. I fully understand your meaning. If necessary, I will open an issue in the official repository. By the way, MBHT is a nice work.
