### ISSUE TITLE
关于数据集的疑问

### ISSUE THREAD

**Issue by ShowTBC** [yuh-yang/MBHT-KDD22#7]
您好：
       由于您提供的数据集中没有用户信息，注意到您是将每个用户的交互序列进行扩充得到的数据集，能否提供一份扩充前的数据集或者关于您的数据集预处理的脚本，我的邮箱是1805819646@qq.com。
       希望能得到您的答复，非常感谢！

**Comment by yuh-yang** [comment]
你好！可以参考这个issue获取原始数据集：
https://github.com/yuh-yang/MBHT-KDD22/issues/6
