### ISSUE TITLE
A confusion about the data

### ISSUE THREAD

**Issue by JuweiChan** [yuh-yang/MBHT-KDD22#8]
Hi, sorry to bother you, i have a confusion about the input data.
I notice that there are four feature columns in training data, what's the meaning of the last column i.e. "item_id"? And I notice that this column is  called "last buy" in the model script, so does it indicate an immediate following target behavior i.e. a purchase after a session?
Please kindly point out my mistakes in understanding. Looking forward to your reply.

**Comment by yuh-yang** [comment]
Hi, @JunweiChan.

Yes. item_id denotes the target item to be predicted in training. And since our learning objective is aimed for buying behaviors, this is also the alias of last buy.
